version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "0:5000"
    volumes:
      - ./backend:/app 
      - /app/node_modules 
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
      - REDIS_HOST=redis
    command: npm run dev 

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app  
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    command: npm run dev 

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  mongo_data:
