version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app  
      - /app/node_modules
    depends_on:
      - redis
      - mongo
    environment:
      - NODE_ENV=development
    command: npm run dev 

tests:
  build: ./frontend
  volumes:
    - ./frontend:/app
    - /app/node_modules
  environment:
    - CI=true
  command: sh -c "[[ \"$CI\" == \"true\" ]] && npm run test || npm run test:watch"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  mongo_data:
