name: Docker Compose CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Start Docker Compose with all services
      - name: Start Docker Compose services
        run: docker compose up -d

      # 3) Wait for MongoDB & Redis to be ready
      - name: Wait for MongoDB & Redis
        run: |
          echo "Waiting for MongoDB & Redis..."
          for i in {1..30}; do
            if docker compose exec mongo mongosh --eval "db.runCommand({ ping: 1 })" &>/dev/null && \
               docker compose exec redis redis-cli ping | grep PONG &>/dev/null; then
              echo "✅ MongoDB & Redis are ready!"
              exit 0
            fi
            echo "⏳ Waiting for services to be ready..."
            sleep 3
          done
          echo "❌ MongoDB or Redis did not start in time."
          exit 1

      # 4) Wait for frontend to be ready (if API is required)
      - name: Wait for Frontend (if needed)
        run: |
          echo "Waiting for Frontend to be ready..."
          for i in {1..30}; do
            if curl -sSf http://localhost:3000 &>/dev/null; then
              echo "✅ Frontend is ready!"
              exit 0
            fi
            echo "⏳ Waiting for frontend..."
            sleep 3
          done
          echo "❌ Frontend did not start in time."
          exit 1
          

      # 5) Run tests inside the tests container
      - name: Run tests
        run: docker compose exec tests npm run test

      # 6) Stop and remove containers
      - name: Clean up
        run: docker compose down
