name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out code
      - name: Checkout
        uses: actions/checkout@v3

      # 2) Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3) Build and run docker-compose
      - name: Build and Run Docker Compose
        run: |
          # Build images
          docker-compose build

          # Run containers but override the 'tests' service command
          # so it does `npm run test` instead of `npm run test:watch`
          docker-compose up --exit-code-from tests -d mongo redis

          # Now run tests container
          docker-compose run --rm tests npm run test

          # Finally, shut everything down
          docker-compose down
