name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: |
          docker-compose build

      - name: Start services in background
        run: |
          docker-compose up -d mongo redis frontend
          # If your tests require `frontend` running, keep it. Otherwise you can omit `frontend`.

      - name: Run tests container
        run: |
          docker-compose run --rm tests npm run test
          # If your `tests` service's default command is "npm run test:watch"
          # override it here so that it exits upon completion:
          # docker-compose run --rm tests npm run test

      - name: Tear down
        if: always()
        run: |
          docker-compose down
