name: Docker Compose Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your code
      - uses: actions/checkout@v3

      # 2) Use compose-action to spin up containers in the background
      - name: Run docker compose (bring containers up)
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          # Path to your docker-compose.yml
          # If it is in the repo root, use `compose-file: "docker-compose.yml"`
          # If it is in `docker/`, use e.g. `compose-file: "./docker/docker-compose.yml"`
          compose-file: "docker-compose.yml"

          # By default, this action does `docker compose up -d`
          # Which means all your services are running in the background

      # 3) Execute tests in the running `tests` service
      - name: Execute tests in the `tests` service
        run: |
          # We'll override the default "npm run test:watch" so it doesn't hang.
          # If your service is literally named `tests` in docker-compose, do:
          docker compose exec tests npm run test
